### ISSUE TITLE
关于压缩日志和文件过期时间

### ISSUE THREAD

**Issue by xxxiaokay** [HiJesse/Android-NativeLogger#1]
请问
1.调用了zipLogs方法后,执行log文件压缩打包后,是否将被压缩的原log文件删除了?
2.配置.expiredPeriod(3),是否为删除创建时间距今有3天的所有log文件,包不包括zip?

**Comment by HiJesse** [comment]
@xxxiaokay 
1. 原log文件是不删除的
2. 设置了过期时间后会清除log目录下所过期的文件, 包含zip

**Comment by xxxiaokay** [comment]
ok,感谢回复

**Comment by HiJesse** [comment]
@xxxiaokay 不好意思 最近没注意这个项目
